services:

  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 9000

  rest-mvc:
    container_name: rest-mvc
    image: restmvc:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    environment:
      - SPRING_PROFILES_ACTIVE=localmysql
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
      - SPRING_DATASOURCE_URL=mysql
      - SERVER_PORT=8080

  reactive:
    container_name: reactive
    image: spring6datar2dbc:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
      - SERVER_PORT=8080

  reactive-mongo:
    container_name: reactive-mongo
    image: reactivemongo:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
      - SERVER_PORT=8080
      - MONGO_ADDRESS=mymongo

  gateway:
    container_name: gateway
    image: spring6gateway:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
    depends_on:
      - auth-server
      - rest-mvc
      - reactive
      - reactive-mongo